// Note:-> Ye project banane se pahle mai zomato ke website pe gya aur waha pe jakr insept kiya aur network me gaya aur waha pe select kiya Fetch/XHR select kiya aur kuch file aaya usme se selct kiya home samajhne ke liye,

// Agr Home naa mile to scroll kre zomato website pe uske baad aa jayegaa.

const restaurants = [
  {
    image: "Eight",
    name: "Golden Spoon",
    rating: 4,
    foodTypes: "Fast Food",
    Price_for_two: 872,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "1.6",
    offers: "17%",
    Alchol_servers: false,
    Restaurant_open_time: "4 AM",
    Restaurant_close_time: "4 PM",
  },
  {
    image: "seventh",
    name: "Curry Palace",
    rating: 4,
    foodTypes: "Thai",
    Price_for_two: 2143,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "1.8",
    offers: "24%",
    Alchol_servers: false,
    Restaurant_open_time: "4 PM",
    Restaurant_close_time: "4 AM",
  },
  {
    image: "nine",
    name: "Golden Spoon",
    rating: 1,
    foodTypes: "Italian",
    Price_for_two: 1531,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "3.9",
    offers: "30%",
    Alchol_servers: false,
    Restaurant_open_time: "11 AM",
    Restaurant_close_time: "11 PM",
  },
  {
    image: "fourth",
    name: "Spice Hub",
    rating: 4,
    foodTypes: "Indian",
    Price_for_two: 407,
    delhiLocations: "Rohini",
    Distance_from_Customer_house: "1.9",
    offers: "17%",
    Alchol_servers: false,
    Restaurant_open_time: "4 AM",
    Restaurant_close_time: "4 PM",
  },
  {
    image: "sixth",
    name: "Desi Delight",
    rating: 3,
    foodTypes: "Indian",
    Price_for_two: 335,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "9.5",
    offers: "17%",
    Alchol_servers: false,
    Restaurant_open_time: "8 AM",
    Restaurant_close_time: "8 PM",
  },
  {
    image: "nine",
    name: "Biryani House",
    rating: 1,
    foodTypes: "Continental",
    Price_for_two: 714,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "3.6",
    offers: "17%",
    Alchol_servers: false,
    Restaurant_open_time: "12 AM",
    Restaurant_close_time: "12 PM",
  },
  {
    image: "fourth",
    name: "Street Treats",
    rating: 5,
    foodTypes: "Indian",
    Price_for_two: 2312,
    delhiLocations: "Janakpuri",
    Distance_from_Customer_house: "3.9",
    offers: "10%",
    Alchol_servers: false,
    Restaurant_open_time: "2 AM",
    Restaurant_close_time: "2 PM",
  },
  {
    image: "tenth",
    name: "Cafe Cravings",
    rating: 1,
    foodTypes: "Continental",
    Price_for_two: 846,
    delhiLocations: "Rohini",
    Distance_from_Customer_house: "9.2",
    offers: "23%",
    Alchol_servers: false,
    Restaurant_open_time: "3 AM",
    Restaurant_close_time: "3 PM",
  },
  {
    image: "second",
    name: "Grill Nation",
    rating: 2,
    foodTypes: "Thai",
    Price_for_two: 2436,
    delhiLocations: "Rohini",
    Distance_from_Customer_house: "1.2",
    offers: "15%",
    Alchol_servers: false,
    Restaurant_open_time: "9 AM",
    Restaurant_close_time: "9 PM",
  },
  {
    image: "sixth",
    name: "Spice Hub",
    rating: 1,
    foodTypes: "Indian",
    Price_for_two: 1327,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "8.0",
    offers: "24%",
    Alchol_servers: false,
    Restaurant_open_time: "6 PM",
    Restaurant_close_time: "6 AM",
  },
  {
    image: "First",
    name: "Spice Hub",
    rating: 2,
    foodTypes: "South Indian",
    Price_for_two: 1007,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "7.9",
    offers: "12%",
    Alchol_servers: true,
    Restaurant_open_time: "7 AM",
    Restaurant_close_time: "7 PM",
  },
  {
    image: "seventh",
    name: "Biryani House",
    rating: 3,
    foodTypes: "Mexican",
    Price_for_two: 2498,
    delhiLocations: "South Extension",
    Distance_from_Customer_house: "3.0",
    offers: "30%",
    Alchol_servers: false,
    Restaurant_open_time: "5 AM",
    Restaurant_close_time: "5 PM",
  },
  {
    image: "sixth",
    name: "Food Fiesta",
    rating: 3,
    foodTypes: "Indian",
    Price_for_two: 2242,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "3.6",
    offers: "3%",
    Alchol_servers: true,
    Restaurant_open_time: "1 AM",
    Restaurant_close_time: "1 PM",
  },
  {
    image: "seventh",
    name: "Flavors of India",
    rating: 1,
    foodTypes: "Fast Food",
    Price_for_two: 2129,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "9.0",
    offers: "12%",
    Alchol_servers: false,
    Restaurant_open_time: "9 PM",
    Restaurant_close_time: "9 AM",
  },
  {
    image: "second",
    name: "Chaat Corner",
    rating: 4,
    foodTypes: "Thai",
    Price_for_two: 230,
    delhiLocations: "Rajouri Garden",
    Distance_from_Customer_house: "9.9",
    offers: "3%",
    Alchol_servers: false,
    Restaurant_open_time: "5 AM",
    Restaurant_close_time: "5 PM",
  },
  {
    image: "sixth",
    name: "Golden Spoon",
    rating: 2,
    foodTypes: "Desserts",
    Price_for_two: 466,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "9.7",
    offers: "2%",
    Alchol_servers: false,
    Restaurant_open_time: "8 AM",
    Restaurant_close_time: "8 PM",
  },
  {
    image: "First",
    name: "Street Treats",
    rating: 4,
    foodTypes: "Desserts",
    Price_for_two: 2433,
    delhiLocations: "Janakpuri",
    Distance_from_Customer_house: "9.5",
    offers: "29%",
    Alchol_servers: true,
    Restaurant_open_time: "8 PM",
    Restaurant_close_time: "8 AM",
  },
  {
    image: "fourth",
    name: "Street Treats",
    rating: 2,
    foodTypes: "Indian",
    Price_for_two: 901,
    delhiLocations: "Connaught Place",
    Distance_from_Customer_house: "6.4",
    offers: "17%",
    Alchol_servers: false,
    Restaurant_open_time: "2 PM",
    Restaurant_close_time: "2 AM",
  },
  {
    image: "seventh",
    name: "Indian Zaika",
    rating: 3,
    foodTypes: "Mexican",
    Price_for_two: 1989,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "7.0",
    offers: "19%",
    Alchol_servers: true,
    Restaurant_open_time: "1 PM",
    Restaurant_close_time: "1 AM",
  },
  {
    image: "fifth",
    name: "Food Junction",
    rating: 4,
    foodTypes: "Indian",
    Price_for_two: 1240,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "1.4",
    offers: "9%",
    Alchol_servers: false,
    Restaurant_open_time: "8 PM",
    Restaurant_close_time: "8 AM",
  },
  {
    image: "seventh",
    name: "Taste Town",
    rating: 3,
    foodTypes: "South Indian",
    Price_for_two: 1828,
    delhiLocations: "Connaught Place",
    Distance_from_Customer_house: "7.3",
    offers: "17%",
    Alchol_servers: false,
    Restaurant_open_time: "6 PM",
    Restaurant_close_time: "6 AM",
  },
  {
    image: "seventh",
    name: "Grill Nation",
    rating: 5,
    foodTypes: "Continental",
    Price_for_two: 652,
    delhiLocations: "Rohini",
    Distance_from_Customer_house: "2.5",
    offers: "22%",
    Alchol_servers: false,
    Restaurant_open_time: "12 AM",
    Restaurant_close_time: "12 PM",
  },
  {
    image: "fourth",
    name: "Desi Delight",
    rating: 3,
    foodTypes: "Chinese",
    Price_for_two: 877,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "10.4",
    offers: "28%",
    Alchol_servers: true,
    Restaurant_open_time: "8 AM",
    Restaurant_close_time: "8 PM",
  },
  {
    image: "second",
    name: "Flavors of India",
    rating: 1,
    foodTypes: "Thai",
    Price_for_two: 1990,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "3.0",
    offers: "18%",
    Alchol_servers: false,
    Restaurant_open_time: "12 PM",
    Restaurant_close_time: "12 AM",
  },
  {
    image: "fourth",
    name: "Food Junction",
    rating: 2,
    foodTypes: "Street Food",
    Price_for_two: 943,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "9.5",
    offers: "20%",
    Alchol_servers: true,
    Restaurant_open_time: "2 AM",
    Restaurant_close_time: "2 PM",
  },
  {
    image: "sixth",
    name: "Curry Palace",
    rating: 1,
    foodTypes: "South Indian",
    Price_for_two: 555,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "6.1",
    offers: "15%",
    Alchol_servers: false,
    Restaurant_open_time: "12 AM",
    Restaurant_close_time: "12 PM",
  },
  {
    image: "tenth",
    name: "Biryani House",
    rating: 2,
    foodTypes: "Street Food",
    Price_for_two: 440,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "6.3",
    offers: "9%",
    Alchol_servers: true,
    Restaurant_open_time: "3 PM",
    Restaurant_close_time: "3 AM",
  },
  {
    image: "First",
    name: "Flavors of India",
    rating: 4,
    foodTypes: "Thai",
    Price_for_two: 842,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "6.8",
    offers: "15%",
    Alchol_servers: true,
    Restaurant_open_time: "3 AM",
    Restaurant_close_time: "3 PM",
  },
  {
    image: "fourth",
    name: "Curry Palace",
    rating: 4,
    foodTypes: "Italian",
    Price_for_two: 1084,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "6.5",
    offers: "2%",
    Alchol_servers: false,
    Restaurant_open_time: "11 AM",
    Restaurant_close_time: "11 PM",
  },
  {
    image: "fourth",
    name: "Spice Hub",
    rating: 4,
    foodTypes: "South Indian",
    Price_for_two: 1711,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "1.2",
    offers: "19%",
    Alchol_servers: true,
    Restaurant_open_time: "1 PM",
    Restaurant_close_time: "1 AM",
  },
  {
    image: "nine",
    name: "Curry Palace",
    rating: 2,
    foodTypes: "Street Food",
    Price_for_two: 1310,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "4.6",
    offers: "28%",
    Alchol_servers: false,
    Restaurant_open_time: "8 AM",
    Restaurant_close_time: "8 PM",
  },
  {
    image: "First",
    name: "Flavors of India",
    rating: 1,
    foodTypes: "Mexican",
    Price_for_two: 1752,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "6.7",
    offers: "23%",
    Alchol_servers: true,
    Restaurant_open_time: "9 PM",
    Restaurant_close_time: "9 AM",
  },
  {
    image: "fourth",
    name: "Food Fiesta",
    rating: 1,
    foodTypes: "Indian",
    Price_for_two: 153,
    delhiLocations: "Janakpuri",
    Distance_from_Customer_house: "2.9",
    offers: "9%",
    Alchol_servers: true,
    Restaurant_open_time: "5 PM",
    Restaurant_close_time: "5 AM",
  },
  {
    image: "First",
    name: "Desi Delight",
    rating: 4,
    foodTypes: "Street Food",
    Price_for_two: 1490,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "4.4",
    offers: "2%",
    Alchol_servers: false,
    Restaurant_open_time: "8 AM",
    Restaurant_close_time: "8 PM",
  },
  {
    image: "sixth",
    name: "The Food Court",
    rating: 2,
    foodTypes: "Mexican",
    Price_for_two: 512,
    delhiLocations: "Janakpuri",
    Distance_from_Customer_house: "1.2",
    offers: "22%",
    Alchol_servers: false,
    Restaurant_open_time: "11 AM",
    Restaurant_close_time: "11 PM",
  },
  {
    image: "sixth",
    name: "Flavors of India",
    rating: 1,
    foodTypes: "Thai",
    Price_for_two: 2345,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "6.9",
    offers: "2%",
    Alchol_servers: false,
    Restaurant_open_time: "4 AM",
    Restaurant_close_time: "4 PM",
  },
  {
    image: "sixth",
    name: "Cafe Cravings",
    rating: 1,
    foodTypes: "Mexican",
    Price_for_two: 2330,
    delhiLocations: "South Extension",
    Distance_from_Customer_house: "5.3",
    offers: "22%",
    Alchol_servers: true,
    Restaurant_open_time: "4 PM",
    Restaurant_close_time: "4 AM",
  },
  {
    image: "nine",
    name: "Taste Town",
    rating: 4,
    foodTypes: "Chinese",
    Price_for_two: 2146,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "10.1",
    offers: "13%",
    Alchol_servers: false,
    Restaurant_open_time: "7 PM",
    Restaurant_close_time: "7 AM",
  },
  {
    image: "sixth",
    name: "Desi Delight",
    rating: 4,
    foodTypes: "Italian",
    Price_for_two: 1967,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "3.0",
    offers: "9%",
    Alchol_servers: false,
    Restaurant_open_time: "9 AM",
    Restaurant_close_time: "9 PM",
  },
  {
    image: "fifth",
    name: "The Food Court",
    rating: 5,
    foodTypes: "Street Food",
    Price_for_two: 2271,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "5.3",
    offers: "9%",
    Alchol_servers: true,
    Restaurant_open_time: "12 AM",
    Restaurant_close_time: "12 PM",
  },
  {
    image: "nine",
    name: "Biryani House",
    rating: 1,
    foodTypes: "Chinese",
    Price_for_two: 1822,
    delhiLocations: "Janakpuri",
    Distance_from_Customer_house: "2.8",
    offers: "16%",
    Alchol_servers: false,
    Restaurant_open_time: "10 PM",
    Restaurant_close_time: "10 AM",
  },
  {
    image: "second",
    name: "Desi Delight",
    rating: 3,
    foodTypes: "Desserts",
    Price_for_two: 1461,
    delhiLocations: "Rajouri Garden",
    Distance_from_Customer_house: "9.5",
    offers: "2%",
    Alchol_servers: false,
    Restaurant_open_time: "1 AM",
    Restaurant_close_time: "1 PM",
  },
  {
    image: "fourth",
    name: "Masala Magic",
    rating: 1,
    foodTypes: "Italian",
    Price_for_two: 885,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "9.1",
    offers: "30%",
    Alchol_servers: true,
    Restaurant_open_time: "1 AM",
    Restaurant_close_time: "1 PM",
  },
  {
    image: "tenth",
    name: "Desi Delight",
    rating: 4,
    foodTypes: "Continental",
    Price_for_two: 1374,
    delhiLocations: "Janakpuri",
    Distance_from_Customer_house: "10.8",
    offers: "21%",
    Alchol_servers: false,
    Restaurant_open_time: "4 PM",
    Restaurant_close_time: "4 AM",
  },
  {
    image: "second",
    name: "Chaat Corner",
    rating: 2,
    foodTypes: "Chinese",
    Price_for_two: 1650,
    delhiLocations: "South Extension",
    Distance_from_Customer_house: "3.1",
    offers: "5%",
    Alchol_servers: false,
    Restaurant_open_time: "7 PM",
    Restaurant_close_time: "7 AM",
  },
  {
    image: "fifth",
    name: "Golden Spoon",
    rating: 5,
    foodTypes: "Thai",
    Price_for_two: 1138,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "7.9",
    offers: "15%",
    Alchol_servers: false,
    Restaurant_open_time: "2 AM",
    Restaurant_close_time: "2 PM",
  },
  {
    image: "nine",
    name: "Taste Town",
    rating: 5,
    foodTypes: "Chinese",
    Price_for_two: 930,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "6.9",
    offers: "17%",
    Alchol_servers: false,
    Restaurant_open_time: "4 AM",
    Restaurant_close_time: "4 PM",
  },
  {
    image: "nine",
    name: "Grill Nation",
    rating: 4,
    foodTypes: "Street Food",
    Price_for_two: 1340,
    delhiLocations: "Rohini",
    Distance_from_Customer_house: "9.4",
    offers: "8%",
    Alchol_servers: true,
    Restaurant_open_time: "7 AM",
    Restaurant_close_time: "7 PM",
  },
  {
    image: "fifth",
    name: "Masala Magic",
    rating: 3,
    foodTypes: "Italian",
    Price_for_two: 688,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "9.7",
    offers: "8%",
    Alchol_servers: true,
    Restaurant_open_time: "3 PM",
    Restaurant_close_time: "3 AM",
  },
  {
    image: "fifth",
    name: "Cafe Cravings",
    rating: 2,
    foodTypes: "Indian",
    Price_for_two: 1803,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "6.7",
    offers: "10%",
    Alchol_servers: false,
    Restaurant_open_time: "6 PM",
    Restaurant_close_time: "6 AM",
  },
  {
    image: "fourth",
    name: "Chaat Corner",
    rating: 3,
    foodTypes: "Continental",
    Price_for_two: 1120,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "9.5",
    offers: "21%",
    Alchol_servers: false,
    Restaurant_open_time: "4 AM",
    Restaurant_close_time: "4 PM",
  },
  {
    image: "First",
    name: "Food Fiesta",
    rating: 2,
    foodTypes: "Continental",
    Price_for_two: 1752,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "1.5",
    offers: "26%",
    Alchol_servers: false,
    Restaurant_open_time: "10 AM",
    Restaurant_close_time: "10 PM",
  },
  {
    image: "First",
    name: "The Food Court",
    rating: 2,
    foodTypes: "Continental",
    Price_for_two: 1449,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "2.0",
    offers: "9%",
    Alchol_servers: false,
    Restaurant_open_time: "11 AM",
    Restaurant_close_time: "11 PM",
  },
  {
    image: "third",
    name: "Desi Delight",
    rating: 4,
    foodTypes: "Indian",
    Price_for_two: 198,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "1.4",
    offers: "4%",
    Alchol_servers: false,
    Restaurant_open_time: "3 AM",
    Restaurant_close_time: "3 PM",
  },
  {
    image: "sixth",
    name: "Urban Bites",
    rating: 3,
    foodTypes: "Street Food",
    Price_for_two: 1485,
    delhiLocations: "Rohini",
    Distance_from_Customer_house: "4.8",
    offers: "19%",
    Alchol_servers: false,
    Restaurant_open_time: "1 AM",
    Restaurant_close_time: "1 PM",
  },
  {
    image: "Eight",
    name: "Masala Magic",
    rating: 1,
    foodTypes: "Indian",
    Price_for_two: 1630,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "10.4",
    offers: "4%",
    Alchol_servers: false,
    Restaurant_open_time: "10 AM",
    Restaurant_close_time: "10 PM",
  },
  {
    image: "tenth",
    name: "Indian Zaika",
    rating: 1,
    foodTypes: "South Indian",
    Price_for_two: 2351,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "10.6",
    offers: "7%",
    Alchol_servers: false,
    Restaurant_open_time: "2 PM",
    Restaurant_close_time: "2 AM",
  },
  {
    image: "second",
    name: "Grill Nation",
    rating: 2,
    foodTypes: "Fast Food",
    Price_for_two: 2243,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "6.1",
    offers: "27%",
    Alchol_servers: true,
    Restaurant_open_time: "8 PM",
    Restaurant_close_time: "8 AM",
  },
  {
    image: "First",
    name: "Street Treats",
    rating: 3,
    foodTypes: "Italian",
    Price_for_two: 782,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "3.2",
    offers: "1%",
    Alchol_servers: false,
    Restaurant_open_time: "2 PM",
    Restaurant_close_time: "2 AM",
  },
  {
    image: "third",
    name: "Street Treats",
    rating: 2,
    foodTypes: "Continental",
    Price_for_two: 1010,
    delhiLocations: "Rohini",
    Distance_from_Customer_house: "9.6",
    offers: "28%",
    Alchol_servers: true,
    Restaurant_open_time: "9 AM",
    Restaurant_close_time: "9 PM",
  },
  {
    image: "First",
    name: "Food Fiesta",
    rating: 4,
    foodTypes: "Chinese",
    Price_for_two: 1144,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "10.7",
    offers: "16%",
    Alchol_servers: true,
    Restaurant_open_time: "4 AM",
    Restaurant_close_time: "4 PM",
  },
  {
    image: "tenth",
    name: "Desi Delight",
    rating: 3,
    foodTypes: "Indian",
    Price_for_two: 255,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "2.7",
    offers: "13%",
    Alchol_servers: false,
    Restaurant_open_time: "5 PM",
    Restaurant_close_time: "5 AM",
  },
  {
    image: "Eight",
    name: "Biryani House",
    rating: 2,
    foodTypes: "Fast Food",
    Price_for_two: 337,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "10.3",
    offers: "10%",
    Alchol_servers: false,
    Restaurant_open_time: "8 PM",
    Restaurant_close_time: "8 AM",
  },
  {
    image: "third",
    name: "Food Fiesta",
    rating: 1,
    foodTypes: "Mexican",
    Price_for_two: 2400,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "5.5",
    offers: "4%",
    Alchol_servers: false,
    Restaurant_open_time: "7 AM",
    Restaurant_close_time: "7 PM",
  },
  {
    image: "nine",
    name: "Urban Bites",
    rating: 5,
    foodTypes: "Italian",
    Price_for_two: 471,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "10.8",
    offers: "28%",
    Alchol_servers: true,
    Restaurant_open_time: "7 AM",
    Restaurant_close_time: "7 PM",
  },
  {
    image: "Eight",
    name: "Food Junction",
    rating: 4,
    foodTypes: "Desserts",
    Price_for_two: 1442,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "3.9",
    offers: "20%",
    Alchol_servers: false,
    Restaurant_open_time: "9 AM",
    Restaurant_close_time: "9 PM",
  },
  {
    image: "fifth",
    name: "Cafe Cravings",
    rating: 3,
    foodTypes: "Desserts",
    Price_for_two: 1301,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "3.8",
    offers: "11%",
    Alchol_servers: false,
    Restaurant_open_time: "12 PM",
    Restaurant_close_time: "12 AM",
  },
  {
    image: "seventh",
    name: "Biryani House",
    rating: 3,
    foodTypes: "Indian",
    Price_for_two: 1618,
    delhiLocations: "Pitampura",
    Distance_from_Customer_house: "7.4",
    offers: "24%",
    Alchol_servers: false,
    Restaurant_open_time: "3 AM",
    Restaurant_close_time: "3 PM",
  },
  {
    image: "seventh",
    name: "Chaat Corner",
    rating: 3,
    foodTypes: "Thai",
    Price_for_two: 2297,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "6.4",
    offers: "7%",
    Alchol_servers: false,
    Restaurant_open_time: "7 AM",
    Restaurant_close_time: "7 PM",
  },
  {
    image: "tenth",
    name: "Food Fiesta",
    rating: 1,
    foodTypes: "Chinese",
    Price_for_two: 1806,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "3.8",
    offers: "28%",
    Alchol_servers: false,
    Restaurant_open_time: "8 PM",
    Restaurant_close_time: "8 AM",
  },
  {
    image: "Eight",
    name: "Hot & Spicy",
    rating: 1,
    foodTypes: "Indian",
    Price_for_two: 920,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "3.0",
    offers: "21%",
    Alchol_servers: true,
    Restaurant_open_time: "1 AM",
    Restaurant_close_time: "1 PM",
  },
  {
    image: "Eight",
    name: "Chaat Corner",
    rating: 4,
    foodTypes: "South Indian",
    Price_for_two: 1205,
    delhiLocations: "Janakpuri",
    Distance_from_Customer_house: "10.8",
    offers: "29%",
    Alchol_servers: true,
    Restaurant_open_time: "7 AM",
    Restaurant_close_time: "7 PM",
  },
  {
    image: "fourth",
    name: "Hot & Spicy",
    rating: 4,
    foodTypes: "Indian",
    Price_for_two: 1696,
    delhiLocations: "Dwarka",
    Distance_from_Customer_house: "5.2",
    offers: "8%",
    Alchol_servers: true,
    Restaurant_open_time: "5 PM",
    Restaurant_close_time: "5 AM",
  },
  {
    image: "First",
    name: "The Food Court",
    rating: 5,
    foodTypes: "South Indian",
    Price_for_two: 1270,
    delhiLocations: "Rajouri Garden",
    Distance_from_Customer_house: "10.4",
    offers: "1%",
    Alchol_servers: true,
    Restaurant_open_time: "2 PM",
    Restaurant_close_time: "2 AM",
  },
  {
    image: "nine",
    name: "Cafe Cravings",
    rating: 2,
    foodTypes: "Continental",
    Price_for_two: 754,
    delhiLocations: "Janakpuri",
    Distance_from_Customer_house: "8.9",
    offers: "23%",
    Alchol_servers: false,
    Restaurant_open_time: "10 PM",
    Restaurant_close_time: "10 AM",
  },
  {
    image: "fourth",
    name: "The Food Court",
    rating: 3,
    foodTypes: "Chinese",
    Price_for_two: 806,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "5.3",
    offers: "12%",
    Alchol_servers: false,
    Restaurant_open_time: "12 PM",
    Restaurant_close_time: "12 AM",
  },
  {
    image: "tenth",
    name: "Chaat Corner",
    rating: 2,
    foodTypes: "Fast Food",
    Price_for_two: 1095,
    delhiLocations: "South Extension",
    Distance_from_Customer_house: "6.7",
    offers: "2%",
    Alchol_servers: true,
    Restaurant_open_time: "7 AM",
    Restaurant_close_time: "7 PM",
  },
  {
    image: "First",
    name: "Royal Tandoor",
    rating: 3,
    foodTypes: "Fast Food",
    Price_for_two: 453,
    delhiLocations: "Saket",
    Distance_from_Customer_house: "1.5",
    offers: "5%",
    Alchol_servers: false,
    Restaurant_open_time: "10 PM",
    Restaurant_close_time: "10 AM",
  },
  {
    image: "seventh",
    name: "Curry Palace",
    rating: 4,
    foodTypes: "Thai",
    Price_for_two: 2143,
    delhiLocations: "Karol Bagh",
    Distance_from_Customer_house: "1.8",
    offers: "24%",
    Alchol_servers: false,
    Restaurant_open_time: "4 PM",
    Restaurant_close_time: "4 AM",
  },
  {
    image: "nine",
    name: "Golden Spoon",
    rating: 1,
    foodTypes: "Italian",
    Price_for_two: 1531,
    delhiLocations: "Lajpat Nagar",
    Distance_from_Customer_house: "3.9",
    offers: "30%",
    Alchol_servers: false,
    Restaurant_open_time: "11 AM",
    Restaurant_close_time: "11 PM",
  },
];

function getrestaurant(restaurants) {
  const root = document.getElementById("root");
  restaurants.forEach((restaurant) => {
    // Create a card
    // 1.Image
    // 2.Card_Content
    // i. Card_header(Name and rating)
    // ii.card_footer(Food_type and price)
    // iii.Card_location(Restaurant Location, distance)

    // Creating a card
    const card = document.createElement("div");
    card.classList.add("card");

    // Create Image
    const image = document.createElement("img");
    image.src = `Images/${restaurant.image}.jpeg`;

    // card_Content
    const Card_content = document.createElement("div");
    Card_content.classList.add("card-content");

    // Card_header
    const Card_header = document.createElement("div");
    Card_header.classList.add("card-header");

    const h3 = document.createElement("h3");
    h3.textContent = restaurant.name;

    const rate = document.createElement("span");
    rate.textContent = `${restaurant.rating} ⭐`;
    rate.classList.add("rating");

    Card_header.appendChild(h3);
    Card_header.appendChild(rate);

    // card_footer
    const Cart_footer = document.createElement("div");
    Cart_footer.classList.add("card-footer");

    const food = document.createElement("Span");
    food.textContent = restaurant.foodTypes;

    const price = document.createElement("span");
    price.textContent = `₹${restaurant.Price_for_two}`;

    Cart_footer.appendChild(food);
    Cart_footer.appendChild(price);

    // Card_location
    const Cart_location = document.createElement("div");
    Cart_location.classList.add("card-location");

    const location = document.createElement("Span");
    location.textContent = restaurant.delhiLocations;

    const distance = document.createElement("span");
    distance.textContent = `${restaurant.Distance_from_Customer_house} km`;

    Cart_location.appendChild(location);
    Cart_location.appendChild(distance);

    // all three Append to Card_content
    Card_content.appendChild(Card_header);
    Card_content.appendChild(Cart_footer);
    Card_content.appendChild(Cart_location);

    // Append to card
    card.appendChild(image);
    card.appendChild(Card_content);

    // Append to root
    root.appendChild(card);
  });
}

getrestaurant(restaurants);

// now filtering resturant which serve alcohol
document.getElementById("Alcohol").addEventListener("click", () => {
  const result = restaurants.filter((obj) => obj.Alchol_servers);
  //   document.getElementById("root").innerHTML = ""; // ye islye likhe kyuki pahle se sara restaurant present hai jo serve krta hai alcohol aur nhi wala bhi, to pahle hm sara ko clean krenge phhir jo alcohol serve krta hai usko add krenge.
  //   ya we can write for line 1129:--->
  document.getElementById("root").replaceChildren();
  getrestaurant(result);
});

// now filtering resturant which rating is 4.0+
document.getElementById("Rating").addEventListener("click", () => {
  const result = restaurants.filter((obj) => obj.rating > 4.5);
  document.getElementById("root").replaceChildren();
  getrestaurant(result);
});

// Filter pr click krenge to jo hide kiye hai css se use unhide kr rhe jb click ho tb
document.getElementById("Filters").addEventListener("click", () => {
  document.getElementById("filterPopup").classList.remove("hidden");
});

//
document.getElementById("applyFilter").addEventListener("click", () => {
  const element = document.querySelector('input[name="filterOption"]:checked');
  const answer = element.value;

  if (answer === "rating") {
    restaurants.sort((a, b) => b.rating - a.rating);
  } else if (answer === "highLow") {
    restaurants.sort((a, b) => b.Price_for_two - a.Price_for_two);
  } else if (answer === "costLowHigh") {
    restaurants.sort((a, b) => a.Price_for_two - b.Price_for_two);
  } else if (answer === "distance") {
    restaurants.sort(
      (a, b) => a.Distance_from_Customer_house - b.Distance_from_Customer_house
    );
  }
  document.getElementById("filterPopup").classList.add("hidden");
  document.getElementById("root").replaceChildren();
  getrestaurant(restaurants);
});
